services:
  mariadb:
    build:
      context: srcs/mariadb
      dockerfile: Dockerfile
    container_name: gamehub-mariadb
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: gamehub
      MYSQL_USER: gamehub_user
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gamehub-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: gamehub-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    networks:
      - gamehub-network
    restart: unless-stopped

  app:
    build:
      context: srcs/app
      dockerfile: Dockerfile
    container_name: gamehub-app
    secrets:
      - db_password
      - key
      - rawg_api_key
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - KEY_FILE=/run/secrets/key
      - RAWG_API_KEY=/run/secrets/rawg_api_key
    depends_on:
      - mariadb
    networks:
      - gamehub-network
    volumes:
      - app_uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: srcs/frontend
      dockerfile: Dockerfile
    container_name: gamehub-frontend
    networks:
      - gamehub-network
    restart: unless-stopped
    

  nginx:
    build:
      context: srcs/nginx
      dockerfile: Dockerfile
    container_name: gamehub-nginx
    ports:
      - "443:443"
    depends_on:
      - adminer
      - app
      - frontend
    networks:
      - gamehub-network
    restart: unless-stopped

secrets:
  db_root_password:
    file: srcs/secrets/db_root_password.txt
  db_password:
    file: srcs/secrets/db_password.txt
  rawg_api_key:
    file: srcs/secrets/rawg_api_key.txt
  key:
    file: srcs/secrets/key.txt

volumes:
  mariadb_data:
    driver: local
  app_uploads:
    driver: local

networks:
  gamehub-network:
    driver: bridge